### ISSUE TITLE
Warning in the org.eclipse.cbi.targetplatform.parent pom.

### ISSUE THREAD

**Issue by miklossy** [eclipse-cbi/targetplatform-dsl#108]
Currently, there is a warning on the `org.eclipse.tycho` `tycho-packaging-plugin` in the `org.eclipse.cbi.targetplatform.parent` pom.

![screenshot](https://user-images.githubusercontent.com/20393472/81147795-59e2b300-8f7b-11ea-9d96-40e919cc6ad2.png)

Since exactly the same version is defined in the `pluginManagement` section, the version from the `build` section can safely be removed.

**Comment by akurtakov** [comment]
The screenshot shows build still uses tycho 1.3.0. It would be nice to migrate to 1.7.0

**Comment by miklossy** [comment]
Good idea! I will create the corresponding PR.

**Comment by miklossy** [comment]
I created the corresponding PR https://github.com/eclipse-cbi/targetplatform-dsl/pull/110 .
