### ISSUE TITLE
Feature Request: Maven Artifact Support following PDE

### ISSUE THREAD

**Issue by SuperOok** [eclipse-cbi/targetplatform-dsl#115]
Very recently, the m2 Team has released a new feature for PDE to support also Maven artifacts in PDE target platforms. This holds both, for builds in Eclipse PDE and for Tycho.

Here is a detailed article about this new feature: 
[https://läubisoft.gmbh/en/articles/using-maven-artifacts-in-pde-rcp-and-tycho-builds/](https://läubisoft.gmbh/en/articles/using-maven-artifacts-in-pde-rcp-and-tycho-builds/)

It would be great, if this feature would also be available in the target DSL, i.e. it would be required to specify maven dependencies in the text specification and transform them to the corresponding target specification as stated in the article.

**Comment by mbarbero** [comment]
Thanks for reporting this. We welcome patches to add support for such a feature.

**Comment by laeubi** [comment]
> My dsl suggestion would be something like this:

please note that there are probably many repositories one can specify, also note that there are other options as well for a location as @merks pointed out.

Essentially one can construct [MavenTargetLocation](https://github.com/eclipse-m2e/m2e-core/blob/master/org.eclipse.m2e.pde.target/src/org/eclipse/m2e/pde/target/MavenTargetLocation.java) and then call `serialize()`

**Comment by hannesN** [comment]
I implemented the following syntax:

![grafik](https://user-images.githubusercontent.com/878154/208897865-4b6a387a-d063-4e79-a857-0d0ce3e74b9c.png)


Which generates the correct target definition:

![grafik](https://user-images.githubusercontent.com/878154/208897954-168c69df-e6d9-44ed-87ed-04670f916ced.png)

So before I start writing test and formatting code, I want to know, what do you think.

**Comment by hannesN** [comment]
If you want to try it out, I am pushing the current state into my fork at https://github.com/hannesn/targetplatform-dsl/

**Comment by laeubi** [comment]
@hannesN maybe instead of `maven_location` use simply `maven` but in general it looks good to me (even though I not using the target dsl).

**Comment by hannesN** [comment]
> 

Thanks for the feedback. Both of your suggestions make sense. I will change that.

**Comment by merks** [comment]
FYI, I've noticed that in general a dependency can include BND instructions:

https://github.com/eclipse/tm4e/blob/f797d2c6632f5639f32604950e41f02a8664acc0/target-platform/tm4e-target.target#L44-L52

I don't think the dialog provides a field for entering that information though so this is easily overlooked.  I'm not say you must/should support this, it's just an FYI... 

Do you plan to flesh out the feature support for the description, copyright, and license, including their URLs?

**Comment by laeubi** [comment]
> I don't think the dialog provides a field for entering that information though so this is easily overlooked.

![grafik](https://user-images.githubusercontent.com/1331477/208903278-4a8633fe-2dc3-4010-b07f-a26731766221.png)

**Comment by merks** [comment]
That's cool.  😃  I easily overlooked that. 👅 

It's perhaps overkill to try to design a bunch of grammar for this level of BND detail...

**Comment by laeubi** [comment]
m2e just handle this a big fat text-block (aka CDATA) ... The same for feature data...

**Comment by hannesN** [comment]
Yeah I'd like to keep it as simple as possible for now. I am also not planning to resolve/check whether the dependencies can be resolved, although I wrote the code in a way it could be added later.

For now, I suggest a minimum of functionality, which is basically seen in the screenshots above. Formatting will be added, but that would it be. Added more functions should be a new issue if it is really needed.

Regarding the feature descriptions: I don't think those are editable in the dialog as well.

**Comment by laeubi** [comment]
You can edit the feature in the target-source tab... as this is not an option for the dsl, I would recommend to either have a simple textblock that is XML ... or one would need a feature-dsl as well.

**Comment by HannesWell** [comment]
Your proposal looks good so far. 👍🏽
> 
> Essentially one can construct [MavenTargetLocation](https://github.com/eclipse-m2e/m2e-core/blob/master/org.eclipse.m2e.pde.target/src/org/eclipse/m2e/pde/target/MavenTargetLocation.java) and then call `serialize()`

That class is not public API, it is just exported for the pde.ui and marked as 'internal' and IIRC we treated it as such in M2E in the past. I didn't check if you are using that, I just wanted to make aware of that.

**Comment by laeubi** [comment]
> That class is not public API, it is just exported for the pde.ui and marked as 'internal' and IIRC we treated it as such in M2E in the past. I didn't check if you are using that, I just wanted to make aware of that.

Not API of what? Everything regarding targets is actually "not API" and constructing an XML by hand is also "not API", so any construct that wants to build on top of m2e /be compatible has to deal with adjustments in that area and be aware that it is closely coupled to possible changes in that area. So from my side as the "non-api-designer" I can say tha this is the most closest thing one can use to replicate the xml and/or benefit from bugfixes and getting compile error as soon as we change/adjust something ;-)

**Comment by guw** [comment]
Is it possible to re-enable the nightly builds? I'd like to help testing this.
https://download.eclipse.org/cbi/updates/tpd/nightly/latest/index.html

**Comment by merks** [comment]
I just did a build a few minutes ago.  

Sorry, I think I did some builds without promoting them, but mistakenly **assumed** that I had promoted the changes for this issue's PR.  So the following build and all any subsequent builds do/will contain these changes:

https://download.eclipse.org/cbi/updates/tpd/nightly/latest

Apologies for the confusion!

**Comment by guw** [comment]
@hannesN  Got it working for a simple file. However, I noticed that it does not work when the Maven `tpd` file is *included* from another `tpd` file. In this case it generates a `target` file without the Maven location.

**Comment by hannesN** [comment]
I'll look into it, @guw .

**Comment by hannesN** [comment]
I created a new issue for included files. I thought this one is already closed by the MR. See #127 

I already started working on a solution.

**Comment by hannesN** [comment]
I created the PR #128

**Comment by hannesN** [comment]
Should we close this issue?

**Comment by merks** [comment]
@hannesN  Yes, I think you've complete this support and if folks find problems or want additional not-yet-implemented features a new dedicated issue should be opened for it.

Thanks for all your excellent work in this area!  🥇

**Comment by guw** [comment]
@hannesN Do you remember if the support for custom bnd instructions was implemented? I checked the README but it's not documented.

**Comment by hannesN** [comment]
Well, as I am not sure what you mean with that, I guess I didn't implement it.

**Comment by guw** [comment]
@hannesN bnd instructions is the thing you and Ed are discussing [here](https://github.com/merks/simrel-maven/issues/4):
```
		    <instructions><![CDATA[
Bundle-Name:           Bundle derived from maven artifact ${mvnGroupId}:${mvnArtifactId}:${mvnVersion}
version:               ${version_cleanup;${mvnVersion}}
Bundle-SymbolicName:   org.${mvnArtifactId}
Bundle-Version:        ${version}
Import-Package:        *;resolution:=optional
Export-Package:        *;version="${version}";-noimport:=true
DynamicImport-Package: *
]]></instructions>
```

**Comment by merks** [comment]
I also mentioned this in this issue above:

https://github.com/eclipse-cbi/targetplatform-dsl/issues/115#issuecomment-1361235931

**Comment by hannesN** [comment]
@guw Could you open a new issue? I'll try to find some time on Friday to investigate a possible solution.
