### ISSUE TITLE
Legacy repos unavailable

### ISSUE THREAD

**Issue by eposse** [eclipse-cbi/targetplatform-dsl#116]
Hi. The readme states that

"the previous repositories are not working anymore. If you still want legacy versions of this project, please use one of the following two URLs:

https://dl.bintray.com/mbarbero/fr.obeo.releng.targetplatform/ or
https://dl.bintray.com/mbarbero/fr.obeo.releng.targetplatform/latest"

But it looks like those update sites are not working either. 

Is it a matter of permissions or have they been decommissioned as well?

If the later, where could one obtain a legacy version?

Thank you.

**Comment by mbarbero** [comment]
Bintray has been decommissioned (see https://bintray.com and https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) so those update sites are gone. You have to use the latest version now.

I'll update the README.
