### ISSUE TITLE
Access to a p2 repository that needs authentication ? 

### ISSUE THREAD

**Issue by opcoach** [eclipse-cbi/targetplatform-dsl#120]
In my location "URL" { }  the URL expect a login/password authentication. 

In the target definition, we can manage it with the settings.xml for the maven build... 

But when we are editing with the tpd editor, we get an error : no repository found at this URL ...

**Comment by merks** [comment]
I've tried to make it easy to set up a development environment to contribute:

https://github.com/eclipse-cbi/targetplatform-dsl/blob/master/CONTRIBUTING.md

Before I could try to help in detail, I would need a site that requires a password, i.e., I'd need a way to reproduce the problem.  (I would normally expect p2 to automatically prompt for the password when loading a site, but again, I need a way to reproduce such a problem.)

**Comment by merks** [comment]
@opcoach Do you plan to provide  a way that I can reproduce the problem?  If not, and you also don't plan to contribute the fix to the problem yourself, then I might as well close this...

**Comment by opcoach** [comment]
Hi Ed, 
I tried to protect one of my p2 repository with a password, but unfortunately, when I test it, I get an http 429 error .. (too much request at the same time)...  I will try again later. 

Don't you have one to test the oomph configuration as I have seen it can manage login/password on p2 ?

**Comment by merks** [comment]
I did p2 password testing in the past at customer sites with such things, but that was quite a few years back.  Also I tested Oomph setups with GitHub private repos, but even that changed when they switched to requiring a personal access token such that actually logging in to acquire a cookie I could no longer get working.  So no, I don't have any password protected p2 repository that I can test against...

**Comment by opcoach** [comment]
I look at this issue again, and I have copied my public p2 repository https://www.opcoach.com/repository/2022-12/  with this new protected URL :    https://p2pass.opcoach.com

login : test
password : Y{h!I#WGL95O

If you try to reach this URL with your navigator you will have to enter these credentials. I protected the directory access. 

Is that ok ?

**Comment by merks** [comment]
I tried it and this dialog comes up when I try to do completion:

![image](https://user-images.githubusercontent.com/208716/211194492-631786c7-a1d9-4d21-95bb-b702878ac319.png)

If I enter the credential, it works afterwards:

![image](https://user-images.githubusercontent.com/208716/211194631-70e77da0-85dc-4485-b2cf-51563a4651f3.png)

So it's working as expected for me...

What happens if you try to use the repository in the Repository Explorer?  For me it also prompts for credentials...

**Comment by opcoach** [comment]
In eclipse install using the p2 url, I get this error... but this is a 429 error .. may be due to my web site configuration... 


![image](https://user-images.githubusercontent.com/1716878/211195254-53e0a6e2-fee0-42c9-a79b-c4abd41e0841.png)

I updated the tpd editor and it works for me too...  

So I will close this issue as it was focused on tpd editor...
