### ISSUE TITLE
Nightly Builds not build since 2022-11-21 at 05:59 

### ISSUE THREAD

**Issue by hannesN** [eclipse-cbi/targetplatform-dsl#126]
I relly like to use the new maven location feature, but for some reasons the nightly build repository contains a version from 2022-11-21  as latest version.

Could you check what's wrong there. It seems the build job doesn't create any artifacts. Might that be the problem?

**Comment by pcdavid** [comment]
Promotion was apparently disabled on purpose as part of https://github.com/eclipse-cbi/targetplatform-dsl/issues/117:

> I'm also a bit concerned that it appears as if a PR build will promote the results [...] so I comment [...] the promotion out of the Jenkins file...

**Comment by hannesN** [comment]
Weird. A nightly build should be the current state of the code. If you use it, you should be aware of API changes. I am also wondering, when will there be a release for version 3.0.0. The snapshot exists for a while now...

**Comment by pcdavid** [comment]
> A nightly build should be the current state of the code

The current state of the master/main branch, yes. NOT the state of the most recently submitted (and yet unmerged) PR as it was (at least that's what I infer from the message, the build log it references is long gone).

**Comment by hannesN** [comment]
> > A nightly build should be the current state of the code
> 
> The current state of the master/main branch, yes. NOT the state of the most recently submitted (and yet unmerged) PR as it was (at least that's what I infer from the message, the build log it references is long gone).

You are right. But that's what I meant. There is no nightly build for the master since november.

**Comment by merks** [comment]
I've only been kicking off "nightly" builds when there relevant are changes.   I just kicked one off now but I doubt that helps.  

I've not done any milestone builds, nor have any releases planned.   There just seemed to be an endless 3.0.0-SNAPSHOTS previously and had grown stale...

I assume you are looking in the right place:

![image](https://user-images.githubusercontent.com/208716/210256155-c80f735b-4dc5-4314-8764-750f57872b2a.png)

Please tell me specifically where you are looking and what you believe to be missing with links to PRs or issues....
