### ISSUE TITLE
Exclude IUs from list?

### ISSUE THREAD

**Issue by diti0023** [eclipse-cbi/targetplatform-dsl#140]
Is it possible (or planned) to exclude single IUs from a list given by "location"?
What can I do if I need to use a version from another location, while discarding the one from the already defined location?

**Comment by merks** [comment]
No.  You can only specify ranges.  

It is possible in general in p2 to express "negative requirements" as in this example:

![image](https://github.com/eclipse-cbi/targetplatform-dsl/assets/208716/975e1336-1443-4b51-bdaf-9705f42b8680)

I.e., one can set the min/max to 0.

But these resources typically get converted to a *.target and it's just not possible to express such a thing (exclusion) in a *.target file.
