### ISSUE TITLE
Includes from other project

### ISSUE THREAD

**Issue by lgblaumeiser** [eclipse-cbi/targetplatform-dsl#55]
I tried to define a tpd file used as a basic target which is extended project specific. When I have the file in the same project, I can set a relative path in the include operation. But when the included file is outside of the project in another project, the relative path is not working. Also a platform:/resource uri does not work. Is this a bug or do you have an idea what is going wrong?

**Comment by mduft** [comment]
Both projects need to have the xtext nature and the one with the extension must depend in the one containing the common file - according to my xtezt knowledge ;) is that the case?

**Comment by briandealwis** [comment]
`platform:/resource/_projectName_/_path/within/project_` worked for me.

**Comment by merks** [comment]
Both platform resource and relative paths work for me:

![image](https://user-images.githubusercontent.com/208716/188303318-788d0906-7b15-4954-8759-7a72fb370027.png)
