### ISSUE TITLE
None singleton bundles support

### ISSUE THREAD

**Issue by dgolovin** [eclipse-cbi/targetplatform-dsl#56]
Currently none singletons processed as singletons in validation and .target generation. Example is .tpd file referencing three different versions of javax.wsdl from orbit repository. There are at least two problems in none singletons processing:
1. Validation complains about "Duplicated IU 'javax.wsdl' for location";
2. Target file generation includes only one "Duplicated IU" with latest version.

**Comment by mduft** [comment]
Hey. I hit this problem today, and we really need this to be able to include 2 guava versions in the target. I work around this right now by manually adding the second version to the .target file right now, but this is not cool :|

**Comment by haubi** [comment]
Since content like this should be quite common these days: Any updates here?
```
location "https://download.eclipse.org/releases/2024-03/" {
	jakarta.annotation-api [1.3.5,2.0.0)
	jakarta.annotation-api [2.1.1,3.0.0)
}
```

The workaround I use right now is to add two maven artifacts:
```
maven javax.annotation-api scope=compile,test dependencyDepth=none missingManifest=generate includeSources {
	dependency { groupId="jakarta.annotation" artifactId="jakarta.annotation-api" version="1.3.5" }
}
maven jakarta.annotation-api scope=compile,test dependencyDepth=none missingManifest=generate includeSources {
	dependency { groupId="jakarta.annotation" artifactId="jakarta.annotation-api" version="2.1.1" }
}
```

**Comment by merks** [comment]
There's not much active development so generally the things that actually get done basically get done because whomever wants it does the actual work.  

I've tried to make it really easy to set up a development environment to contribute:

https://github.com/eclipse-cbi/targetplatform-dsl/blob/master/CONTRIBUTING.md#setting-up-a-development-environment

I'll review pull requests and answer questions...

**Comment by haubi** [comment]
It turns out that since #130 the editor validator accepts identical IU names having non-overlapping version ranges, but just one of them actually ends up in the generated .target file it seems.

**Comment by merks** [comment]
@haubi 

That seems trickier to fix.  I don't know the implementation details very well.  Are you continuing to investigate.  I'm happy to help where I can.  I have quite a bit of experience with p2 and PDE...

**Comment by haubi** [comment]
Thanks!
And yes, I expect myself to continue here, but with low priority, since there is the maven workaround.

**Comment by haubi** [comment]
Findings for today:
Looking at the testIUOverride* tests, it turns out that it is not too obvious how version overrides should behave when we start to resolve multiple versions.

**Comment by merks** [comment]
This is fixed and available in the latest nightly build:

https://download.eclipse.org/cbi/updates/tpd/nightly/latest

@haubi  Thanks for your contribution!  ❤️  🥇
