### ISSUE TITLE
Error on target creation: HTTP Server Unknown HTTP Response Code 302

### ISSUE THREAD

**Issue by Pontesegger** [eclipse-cbi/targetplatform-dsl#58]
Seems that redirects using 302 response codes do not work when trying to create a target file.

You may try it with the pydev update site:
location "http://pydev.org/updates"

as a workaround I currenty use the redirect target:
location "http://dl.bintray.com/fabioz/pydev/all"

**Comment by merks** [comment]
I don't see that the page produces a 302:

![image](https://user-images.githubusercontent.com/208716/188304665-ad468353-2281-4150-b6ff-97b8a361ce3e.png)
