### ISSUE TITLE
Ignore trailing slash of URL

### ISSUE THREAD

**Issue by Bananeweizen** [eclipse-cbi/targetplatform-dsl#68]
We have a setup, where tpd files are split by components, e.g. xtext.tpd, testing.tpd, graphical.tpd and so on. As all of these are included into one product.tpd, it can happen that multiple component tpd files refer to the same update site URI. Normally those multiple occurences are merged, but not if one uri contains a trailing slash.

E.g. http://my.update.site and http://my.update.site/ are not merged and both occur in the final target file.

All tooling and the generated target file work completely fine. It is just that some developers have been confused by update sites occuring twice in the target definition. This could be avoided by normalizing the URLs.

**Comment by merks** [comment]
The fix is available here:

https://download.eclipse.org/cbi/updates/tpd/
