### ISSUE TITLE
Signing the build artifacts

### ISSUE THREAD

**Issue by erwindl0** [eclipse-cbi/targetplatform-dsl#70]
I've created an Oomph setup for Triquetrum contributors (IDE + workspace), including your very handy TP editor/generator. 

When running the installer, the user gets a warning msg about Unsigned Content for the targetplatform feature and plugins.

![afbeelding](https://cloud.githubusercontent.com/assets/6461921/25086671/8b11e1a2-2369-11e7-94cd-6c2b58a0f21d.png)

As some users may find this annoying, is it possible to sign the build artifacts as Eclipse projects often/must do?

thanks
erwin

**Comment by mbarbero** [comment]
I'm in the process to move this project to Eclipse CBI (see https://bugs.eclipse.org/bugs/show_bug.cgi?id=514622). Once done, the artifacts will be signed with the Eclipse Foundation certificate.

**Comment by erwindl0** [comment]
Great, thanks for the fast feedback and for your work on this great tool!

**Comment by merks** [comment]
The latest update sites contain only signed content.

https://download.eclipse.org/cbi/updates/tpd/
