### ISSUE TITLE
Content type not associated with the editor by default

### ISSUE THREAD

**Issue by pcdavid** [eclipse-cbi/targetplatform-dsl#85]
Versions:
- target-platform-dsl 3.0.0-SNAPSHOT (3.0.0.201809052136)
- Eclipse 2018-12
- Xtext 2.16.0.v20181203-1555

After installing the DSL feature, opening any `.tpd` or `.targetplatform` file still uses the plain text editor. I had to manually go to the _General > Content Types_ preferences page to add the _Target Platform DSL Editor_ to the _Text > Target Platform DSL File_  type and make it the default.

As far a I remember, this used to work out-of-the-box in the previous "legacy" versions.

**Comment by miklossy** [comment]
I have just tested it with the latest version and seems that the content types are associated with the editor properly out-of-the-box:
![image](https://user-images.githubusercontent.com/20393472/79882235-91d1ee00-83f2-11ea-80dd-3e74c4db0536.png)
![image](https://user-images.githubusercontent.com/20393472/79882304-a910db80-83f2-11ea-8564-3ef6b5f92cfb.png)
The content type associations has been added automatically to the TargetPlatform-DSL project by updating it to Xtext 2.14, see [commit](https://github.com/eclipse-cbi/targetplatform-dsl/commit/b4edca4fc285aeaff52dd175eec9171aa4d8e2cd).
@pcdavid : Would be awesome if you could try it out again with the latest snapshot and give feedback.

**Comment by merks** [comment]
Yes, it works for me as well.
