### ISSUE TITLE
Duplicates handling

### ISSUE THREAD

**Issue by mon-compte-github** [eclipse-cbi/targetplatform-dsl#90]
Hi, I've a big app with many dependencies, each of them being packaged as feature in its own p2 repos. Some packages contains shared stuff, and thus are included multiple times in the dependency graph, possibly in different versions.

Simplified example with application A and 2 components, B and C :

```
A ---> B ---> C v1.0.0
   \
    +----> C v1.2.0

---> depends on
```

Each component has it's own .tpd defining it's runtime dependencies. Application's tpd includes B features and its tpd, along with C feature and its tpd. Easy ^^

But when it comes to generating the final target platform, I've two occurrences of C, in different versions. Is there a way to remove duplicated features (i.e same id) only keeping the newest in generated target ? if not, is it possible to extend dsl so that we can define exclusions of some sub-dependencies ?

Proposal :

```
include "http://xxxx/B.tpd" {
   exclude C.feature       // <-- add-on
}

location"http://xxxx/B/p2repo/" {
   B.feature
}

// keep highest version of C
include "http://xxxx/C.tpd"

location"http://xxxx/C/p2repo/" {
   C.feature
}
```

TIA

**Comment by mbarbero** [comment]
If the 2 versions are included, it's because it is required. If you don't expect it, or if it breaks something in your app, I'd recommend revisit your dependencies. 

Having the 2 versions as a result is a feature IMO.
