### ISSUE TITLE
Fails on 2019-03, reporting invalid architecture

### ISSUE THREAD

**Issue by Bananeweizen** [eclipse-cbi/targetplatform-dsl#91]
Target generation fails on 2019-03, if an architecture is specified. For reproduction have this in your *.tpd (I took those architectures directly from a running eclipse.core.Platform):
```
environment PA_RISC ppc sparc x86 x86_64 ia64 ia64_32
```
Reported failure in editor and during generation:
```
Diagnostic of the generation of the target platform.
'PA_RISC' is not a valid environment specification value.
'ppc' is not a valid environment specification value.
'sparc' is not a valid environment specification value.
'x86_64' is not a valid environment specification value.
'ia64' is not a valid environment specification value.
'ia64_32' is not a valid environment specification value.
```
Only x86 is not an error. It seems that the underlying Platform.knownOSArchValues() is not filled the same way anymore.

To be clear: My own target contains only "x86_64", not all of those above. Still, the error is also shown for just one target.

**Comment by mbarbero** [comment]
Well, it seems that this commit has been a bit aggressive https://git.eclipse.org/c/platform/eclipse.platform.runtime.git/commit/bundles/org.eclipse.core.runtime/src/org/eclipse/core/internal/runtime/InternalPlatform.java?id=f3bea867fe4280ae30bd34d2a950a85cac4af424

**Comment by mbarbero** [comment]
I've opened a bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=545655

**Comment by Bananeweizen** [comment]
For everyone else who has this problem (since it may take until the next eclipse release for the underlying fix): As a workaround, I removed the declaration from the TPD, added an Ant builder to the target platform project, and whenever the .target changes, the Ant builder patches the file to contain the architecture again.

**Comment by mbarbero** [comment]
A patch has been provided in https://bugs.eclipse.org/bugs/show_bug.cgi?id=545655. It will be available in the next release (2018-06). I won't provide any fix for this issue in the dsl, marking as won't fix. I'd suggest users to avoid 2018-03 if this is an issue for them.
