### ISSUE TITLE
Updating the Xtext Community Website

### ISSUE THREAD

**Issue by miklossy** [eclipse-cbi/targetplatform-dsl#95]
Hello Eclipse Targetplatform DSL team,

The Xtext team would like to update the [Xtext community website](https://www.eclipse.org/Xtext/community.html) listing all the cool projects people are building around Xtext/Xtend.

See also the corresponding [GitHub issue](https://github.com/eclipse/xtext/issues/1541) and [Bugzilla ticket](https://bugs.eclipse.org/bugs/show_bug.cgi?id=328477).

If you are interested that the Eclipse Targetplatform DSL project is listed there, please provide the following information as a comment to this issue:

```
<tr>
	<td><a href="project_link">project_name</a></td>
	<td>project_description_max_2_sentences</td>
	<td>license</td>
	<td>category</td>
	<td>author(s)</td>
</tr>

```
We will then update the Xtext community website and get it online as soon as possible.

Thanks!
Tamás

**Comment by miklossy** [comment]
I would like to add the `Targetplatform DSL` project to the [Xtext community website](https://www.eclipse.org/Xtext/community.html) as follows

```html
<tr>
	<td><a href="https://github.com/eclipse-cbi/targetplatform-dsl">TargetPlatform DSL</a></td>
	<td>The Target Platform Definition DSL and Generator project provides a DSL with an advanced editor and a generator to generate *.target files from the DSL that Eclipse PDE is able to read to provision a Target Platform.</td>
	<td>EPL</td>
	<td>Tool</td>
	<td>Mikaël Barbero and others</td>
</tr>
```

@mbarbero Do you agree with that?

**Comment by mbarbero** [comment]
Sure, thanks.

**Comment by miklossy** [comment]
The `Target Platform Definition DSL and Generator` project has been added to the [Xtext community website](https://www.eclipse.org/Xtext/community.html).
